name = "bare_core"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Olivier Henley"]
maintainers = ["Olivier Henley <olivier.henley@gmail.com>"]
maintainers-logins = ["ohenley"]

[configuration.variables]
core_type = { type = "Enum", values = ["F", "G", "H", "L", "W"], default = "F" }
core = { type = "Enum", values = ["m4", "m7"], default = "m7" }
float_support = { type = "Enum", values = ["f", "nof"], default = "f" }

[[depends-on]]
bare_types = "0.1.0-dev"